// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtd58ms_ZeT0TWanQJfFf-BpgHzkaiKfM',
    appId: '1:424216711454:web:392de09545a9ad0411790f',
    messagingSenderId: '424216711454',
    projectId: 'chatapptutorial-1d820',
    authDomain: 'chatapptutorial-1d820.firebaseapp.com',
    storageBucket: 'chatapptutorial-1d820.firebasestorage.app',
    measurementId: 'G-F889S8WGMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWTIdctvjz1jaaANGIiqQr9NRZ_IO8gbw',
    appId: '1:424216711454:android:2c79fb59364b979d11790f',
    messagingSenderId: '424216711454',
    projectId: 'chatapptutorial-1d820',
    storageBucket: 'chatapptutorial-1d820.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR7ja5jDssoUwc2D3bRZQzL5W69y-U-8k',
    appId: '1:424216711454:ios:7430be5fddb8235111790f',
    messagingSenderId: '424216711454',
    projectId: 'chatapptutorial-1d820',
    storageBucket: 'chatapptutorial-1d820.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR7ja5jDssoUwc2D3bRZQzL5W69y-U-8k',
    appId: '1:424216711454:ios:7430be5fddb8235111790f',
    messagingSenderId: '424216711454',
    projectId: 'chatapptutorial-1d820',
    storageBucket: 'chatapptutorial-1d820.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtd58ms_ZeT0TWanQJfFf-BpgHzkaiKfM',
    appId: '1:424216711454:web:07d9b266bfc92fa811790f',
    messagingSenderId: '424216711454',
    projectId: 'chatapptutorial-1d820',
    authDomain: 'chatapptutorial-1d820.firebaseapp.com',
    storageBucket: 'chatapptutorial-1d820.firebasestorage.app',
    measurementId: 'G-L6CPVWC5F1',
  );
}
